### ISSUE TITLE
CAD of all sub parts

### ISSUE THREAD

**Issue by Plopao** [JeremieBourque1/projetS4#39]
*LOOK IN THE CARS ABOUT CONVERTING FREE CAD TO SOLIDWORKS FIRST!*

- [x] Gears

- [ ] Axis holding the gears in place

- [ ] Arm segment (tubing)

- [x] Other brackets

**Comment by amelierioux** [comment]
We need to do more measurements of François's arm because we are missing some to complete all the parts.
